/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_828724_4_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_828724_1[] = { "safe", "tap", "unsafe" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_828724_14_axes[] = { 0, 1, 2 };
const uint32_t ei_dsp_config_828724_14_axes_size = 3;
ei_dsp_config_raw_t ei_dsp_config_828724_14 = {
    14, // uint32_t blockId
    1, // int implementationVersion
    3, // int length of axes
    1.0f // float scale-axes
};

const float ei_dn_standard_scaler_mean_828724_14[3] = { 502.35777666131656, 47.70755551702447, 6.935555557674832 };
const float ei_dn_standard_scaler_scale_828724_14[3] = { 0.0017336733471230313, 0.010093211158970041, 0.7691442416126927 };
const float ei_dn_standard_scaler_var_828724_14[3] = { 332709.6940178281, 9816.152157429457, 1.6903802665145586 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_828724_14 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_828724_14,
    .mean_data_len = 3,
    .scale_data = (float *)ei_dn_standard_scaler_scale_828724_14,
    .scale_data_len = 3,
    .var_data = (float *)ei_dn_standard_scaler_var_828724_14,
    .var_data_len = 3
};
ei_data_normalization_t ei_data_normalization_config_828724_14 = {
    (void *) &ei_data_normalization_standard_scaler_config_828724_14, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_828724_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_828724_1[ei_dsp_blocks_828724_1_size] = {
    { // DSP block 14
        14,
        3, // output size
        &extract_raw_features, // DSP function pointer
        (void*)&ei_dsp_config_828724_14, // pointer to config struct
        ei_dsp_config_828724_14_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_828724_14_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_828724_14, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_828724_4 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_828724_4_init,
    .model_invoke = &tflite_learn_828724_4_invoke,
    .model_reset = &tflite_learn_828724_4_reset,
    .model_input = &tflite_learn_828724_4_input,
    .model_output = &tflite_learn_828724_4_output,
};

const uint8_t ei_output_tensors_indices_828724_4[1] = { 0 };
const uint8_t ei_output_tensors_size_828724_4 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_828724_4 = {
    .implementation_version = 1,
    .block_id = 4,
    .output_tensors_indices = ei_output_tensors_indices_828724_4,
    .output_tensors_size = ei_output_tensors_size_828724_4,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_828724_4,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_828724_1_size = 1;
const uint32_t ei_learning_block_828724_4_inputs[1] = { 14 };
const uint8_t ei_learning_block_828724_4_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_828724_1[ei_learning_blocks_828724_1_size] = {
    {
        4,
        &run_nn_inference,
        (void*)&ei_learning_block_config_828724_4,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_828724_4_inputs,
        ei_learning_block_828724_4_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_828724_4 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_828724_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_828724_1[ei_postprocessing_blocks_828724_1_size] = {
    {
        .block_id = 4,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_828724_4,
        .input_block_id = 4
    },
};

const uint8_t freeform_outputs_828724_1_size = 0;

uint32_t *freeform_outputs_828724_1 = nullptr;

const ei_impulse_t impulse_828724_1 = {
    .project_id = 828724,
    .project_owner = "Shriya Sinha",
    .project_name = "AI Water Classifier",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 7,

    .nn_input_frame_size = 3,
    .raw_sample_count = 1,
    .raw_samples_per_frame = 3,
    .dsp_input_frame_size = 1 * 3,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1,
    .frequency = 0,

    .dsp_blocks_size = ei_dsp_blocks_828724_1_size,
    .dsp_blocks = ei_dsp_blocks_828724_1,

    .learning_blocks_size = ei_learning_blocks_828724_1_size,
    .learning_blocks = ei_learning_blocks_828724_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_828724_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_828724_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "TDS + Turbidity + pH",
    .slice_size = (1/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 3,
    .categories = ei_classifier_inferencing_categories_828724_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_828724_1_size,
    .freeform_outputs = freeform_outputs_828724_1
};

ei_impulse_handle_t impulse_handle_828724_1 = ei_impulse_handle_t( &impulse_828724_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_828724_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_828724_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_828724_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_828724_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
